#!/usr/bin/env bash
# rollout-language-gate.sh — Bulk-add language-gate to every repo in an org
#
# This script:
#   1. Lists all repos in a GitHub org
#   2. For each repo, creates a branch with:
#      - .language-policy.toml (auto-classified based on repo content)
#      - .github/workflows/language-gate-caller.yml (calls the shared workflow)
#   3. Opens a PR for each repo
#
# Usage:
#   ./rollout-language-gate.sh hyperpolymath
#   ./rollout-language-gate.sh metadatastician --dry-run
#
# Requirements: gh (authenticated), jq, git

set -euo pipefail

# ─── Configuration ──────────────────────────────────────────────────────────

GATE_WORKFLOW_REF="hyperpolymath/.github/.github/workflows/language-gate.yml@main"
BRANCH_NAME="chore/add-language-gate"
PR_TITLE="Add language gate CI policy"
DRY_RUN=false

# ─── Argument parsing ──────────────────────────────────────────────────────

ORG="${1:?Usage: $0 <github-org> [--dry-run]}"
[[ "${2:-}" == "--dry-run" ]] && DRY_RUN=true

# ─── Auto-classify a repo ─────────────────────────────────────────────────

auto_classify() {
  local repo_path="$1"
  local role="core"
  local extra_allowed=""
  local provers="gnatprove"
  local runtime="bun"
  local ffi="hexadeca"
  local beam="snif"

  # Community adapter detection
  local repo_name
  repo_name=$(basename "$repo_path")

  # Check if this is a language-specific adapter
  case "$repo_name" in
    *-rescript*|*rescript-*) role="community-adapter"; extra_allowed='["ReScript"]' ;;
    *-vlang*|*vlang-*|*-v-*)  role="community-adapter"; extra_allowed='["V"]' ;;
    *-python*|*python-*)     role="community-adapter"; extra_allowed='["Python"]' ;;
    *-go-*|*go-*)            role="community-adapter"; extra_allowed='["Go"]' ;;
    *-ts-*|*typescript-*)    role="community-adapter"; extra_allowed='["TypeScript"]' ;;
    poly-*-mcp)              role="deprecated" ;;  # Moving to boj-server
  esac

  # If repo has Rust, check for existing prover
  if find "$repo_path" -name "Cargo.toml" -not -path "*/target/*" 2>/dev/null | head -1 | grep -q .; then
    if grep -rql 'kani' "$repo_path" --include='*.rs' --include='*.toml' 2>/dev/null; then
      provers="kani"
    elif grep -rql 'creusot' "$repo_path" --include='*.rs' --include='*.toml' 2>/dev/null; then
      provers="creusot"
    elif grep -rql 'prusti' "$repo_path" --include='*.rs' --include='*.toml' 2>/dev/null; then
      provers="prusti"
    elif grep -rql 'verus' "$repo_path" --include='*.rs' --include='*.toml' 2>/dev/null; then
      provers="verus"
    fi
  fi

  # If no Rust, no prover needed
  if ! find "$repo_path" -name "*.rs" -not -path "*/target/*" 2>/dev/null | head -1 | grep -q .; then
    provers=""
  fi

  # If repo is primarily Idris2
  if find "$repo_path" -name "*.idr" 2>/dev/null | head -1 | grep -q .; then
    provers="idris2-typecheck"
  fi

  # If no JS/TS at all
  if ! find "$repo_path" \( -name "*.ts" -o -name "*.js" -o -name "*.tsx" -o -name "*.jsx" \) \
       -not -path "*/node_modules/*" 2>/dev/null | head -1 | grep -q .; then
    runtime="none"
  fi

  # If no BEAM code
  if ! find "$repo_path" \( -name "*.erl" -o -name "*.ex" -o -name "*.exs" \) 2>/dev/null | head -1 | grep -q .; then
    beam="none"
  fi

  # If this IS the hexadeca adapter
  if [[ "$repo_name" == *hexadeca* ]]; then
    ffi="direct"
  fi

  # Generate the policy file
  cat << TOML
# Auto-generated by rollout-language-gate.sh
# Review and adjust before merging.

[policy]
role = "$role"

[allowed_languages]
extra_allowed = ${extra_allowed:-[]}

[provers]
required = $(if [[ -n "$provers" ]]; then echo "[\"$provers\"]"; else echo "[]"; fi)

[runtime]
js = "$runtime"

[ffi]
method = "$ffi"

[beam]
native = "$beam"

[abi]
method = "idrisiser"
TOML
}

# ─── Generate caller workflow ──────────────────────────────────────────────

generate_caller_workflow() {
  cat << 'YAML'
# Auto-generated — calls the shared language-gate workflow
name: Language Gate

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  language-gate:
    uses: GATE_WORKFLOW_REF
YAML
}

# ─── Main loop ─────────────────────────────────────────────────────────────

echo "Rollout language-gate to org: $ORG"
[[ "$DRY_RUN" == true ]] && echo "(DRY RUN — no changes will be made)"
echo ""

# Get all non-archived, non-fork repos
REPOS=$(gh repo list "$ORG" --limit 1000 --no-archived --source --json name -q '.[].name')

TOTAL=$(echo "$REPOS" | wc -l)
CURRENT=0
SKIPPED=0
CREATED=0
FAILED=0

for repo_name in $REPOS; do
  CURRENT=$((CURRENT + 1))
  echo "[$CURRENT/$TOTAL] $ORG/$repo_name"

  # Clone shallowly
  tmpdir=$(mktemp -d)
  if ! gh repo clone "$ORG/$repo_name" "$tmpdir/$repo_name" -- --depth 1 --quiet 2>/dev/null; then
    echo "  ✗ Clone failed — skipping"
    FAILED=$((FAILED + 1))
    rm -rf "$tmpdir"
    continue
  fi

  cd "$tmpdir/$repo_name"

  # Check if already has language gate
  if [[ -f ".language-policy.toml" ]]; then
    echo "  ⊘ Already has .language-policy.toml — skipping"
    SKIPPED=$((SKIPPED + 1))
    cd /
    rm -rf "$tmpdir"
    continue
  fi

  # Check if branch already exists
  if git ls-remote --heads origin "$BRANCH_NAME" 2>/dev/null | grep -q .; then
    echo "  ⊘ Branch $BRANCH_NAME already exists — skipping"
    SKIPPED=$((SKIPPED + 1))
    cd /
    rm -rf "$tmpdir"
    continue
  fi

  if [[ "$DRY_RUN" == true ]]; then
    echo "  → Would create:"
    echo "    .language-policy.toml (role: $(auto_classify . | grep 'role' | head -1 | awk -F'"' '{print $2}'))"
    echo "    .github/workflows/language-gate-caller.yml"
    cd /
    rm -rf "$tmpdir"
    continue
  fi

  # Create branch
  git checkout -b "$BRANCH_NAME" 2>/dev/null

  # Generate and write policy file
  auto_classify . > .language-policy.toml

  # Generate and write caller workflow
  mkdir -p .github/workflows
  generate_caller_workflow | sed "s|GATE_WORKFLOW_REF|$GATE_WORKFLOW_REF|" > .github/workflows/language-gate-caller.yml

  # Commit and push
  git add .language-policy.toml .github/workflows/language-gate-caller.yml
  git commit -m "chore: add language gate CI policy

Adds .language-policy.toml and language-gate workflow caller.
Auto-classified role based on repo content — review before merging.

Part of estate-wide migration to enforce language bans, formal
verification requirements, and architectural patterns (hexadeca,
SNIF, Bun, idrisiser)." --quiet

  git push origin "$BRANCH_NAME" --quiet 2>/dev/null

  # Create PR
  ROLE=$(grep 'role' .language-policy.toml | head -1 | awk -F'"' '{print $2}')
  gh pr create \
    --title "$PR_TITLE" \
    --body "## Auto-generated language gate policy

**Detected role:** \`$ROLE\`

This PR adds:
- \`.language-policy.toml\` — declares this repo's language/architecture policy
- \`.github/workflows/language-gate-caller.yml\` — calls the shared language-gate workflow

**Please review the policy file** — the role and settings were auto-detected but may need adjustment.

### What this enforces
- Banned language detection (Go, Python, TS, etc. unless exempted)
- Formal verification prover requirements (GNATprove/Kani/Creusot/Prusti/Verus)
- Runtime policy (Bun, not Deno/Node)
- FFI policy (hexadeca adapter, not direct)
- BEAM interop (SNIF, not NIF)

Part of the estate-wide migration plan." \
    --head "$BRANCH_NAME" 2>/dev/null

  if [[ $? -eq 0 ]]; then
    echo "  ✓ PR created (role: $ROLE)"
    CREATED=$((CREATED + 1))
  else
    echo "  ✗ PR creation failed"
    FAILED=$((FAILED + 1))
  fi

  cd /
  rm -rf "$tmpdir"
done

echo ""
echo "════════════════════════════════════════════════════════════"
echo "  ROLLOUT COMPLETE"
echo "════════════════════════════════════════════════════════════"
echo "  Total repos:  $TOTAL"
echo "  PRs created:  $CREATED"
echo "  Skipped:      $SKIPPED"
echo "  Failed:       $FAILED"
echo "════════════════════════════════════════════════════════════"
